### ISSUE TITLE
PHP 8.2 support

### ISSUE THREAD

**Issue by elcreator** [php/pecl-system-dio#11]
Just built php_dio using manual here https://wiki.php.net/internals/windows/stepbystepbuild_sdk_2
We need PHP 8.2 DLL here https://windows.php.net/downloads/pecl/releases/dio/0.2.1/ as almost year passed since 8.2 release date.
If it's take time to rebuild it manually please consider using Github automation https://github.com/cmb69/setup-php-sdk which can build multiple releases, including upcoming 8.3.

**Comment by elcreator** [comment]
[php_dio-0.2.1-8.2-ts-vs16-x64.zip](https://github.com/php/pecl-system-dio/files/12858334/php_dio-0.2.1-8.2-ts-vs16-x64.zip)

**Comment by remicollet** [comment]
Sorry, I don't know what Windows is

**Comment by cmb69** [comment]
Windows DLLs are available from https://pecl.php.net/package/dio for a while now (built with https://github.com/php/php-windows-builder).
