### ISSUE TITLE
Possible memory leak in dio_read()

### ISSUE THREAD

**Issue by DSEPaul** [php/pecl-system-dio#12]
Hi, I've been testing out various IO options for an application that needs a very high IO throughput.
When testing the DIO functions, I keep getting an error saying I've run out of memory after calling dio_read() multiple times.

Test code
`<?php

#Create a 10KB file
file_put_contents(__DIR__.'/dio-test-file', str_repeat('0', 10 * 1024));

$hFile = dio_open(__DIR__.'/dio-test-file', O_RDONLY);
while(true){
	
	#Go back to the start of the file
	dio_seek($hFile, 0);
	
	#Read some data
	$data = dio_read($hFile, 10000);
}

?>`

I would expect the test code above to sit in the loop reading the first 10,000 bytes from the file over and over until the script is killed.
Instead, the script exits almost immediately with the following error
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 12288 bytes) in /dio-test.php on line 13

**Comment by remicollet** [comment]
Thanks for the report
Confirmed and fixed
0.2.2 will be released shortly

**Comment by DSEPaul** [comment]
Hi, I've updated and re-run my script this morning. Looks like it's working perfectly now.
Thank you for the quick response :)
