### ISSUE TITLE
PHP 8 incompatibility

### ISSUE THREAD

**Issue by cmb69** [php/pecl-system-dio#5]
While there are source code directories for php5 and php7, there is none for php8, so the package cannot be build for recent PHP versions. If there are no plans to support this, it might be a good idea to add the info to package.xml, so users get clearer information why they won't be able to build.

**Comment by remicollet** [comment]
ext work with PHP 8+, probably config.w32 needs to be adapted.

**Comment by cmb69** [comment]
Ah, right! Just submitted #6.
